# Generated by Django 5.1.2 on 2024-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preport", "0005_db_finding_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="db_finding",
            name="display_id",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="db_finding_template",
            name="display_id",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
