# Generated by Django 5.1.4 on 2025-01-30 17:17

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preport", "0007_db_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="db_attackflow",
            name="attackflow_png",
        ),
        migrations.RemoveField(
            model_name="db_attackflow",
            name="finding",
        ),
        migrations.AddField(
            model_name="db_appendix",
            name="report",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="preport.db_report",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="db_attackflow",
            name="attackflow_image",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="db_attackflow",
            name="description",
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name="db_attackflow",
            name="findings",
            field=models.ManyToManyField(
                blank=True, related_name="attackflow_finding", to="preport.db_finding"
            ),
        ),
        migrations.AddField(
            model_name="db_attackflow",
            name="report",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="preport.db_report",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="db_appendix",
            name="description",
            field=martor.models.MartorField(blank=True),
        ),
        migrations.RemoveField(
            model_name="db_appendix",
            name="finding",
        ),
        migrations.AlterField(
            model_name="db_attackflow",
            name="attackflow_afb",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="DB_AttackTree",
        ),
        migrations.AddField(
            model_name="db_appendix",
            name="finding",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="preport.db_finding",
            ),
            preserve_default=False,
        ),
    ]
