# Generated by Django 5.1.4 on 2025-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preport", "0008_remove_db_attackflow_attackflow_png_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="db_appendix",
            name="finding",
        ),
        migrations.AddField(
            model_name="db_appendix",
            name="findings",
            field=models.ManyToManyField(
                blank=True, related_name="appendix_finding", to="preport.db_finding"
            ),
        ),
    ]
